- name: My first play
  hosts: servers
  become: yes
  tasks:
  - name: ls
    shell: |
      mkdir prometheus
      cd prometheus
      
      wget -c https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
      tar xvfz node_exporter-1.7.0.linux-amd64.tar.gz 
      
      sudo echo "[Unit]
      Description=Prometheus Linux Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=root
      Group=root
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target" > /etc/systemd/system/metrics.service

      sudo systemctl daemon-reload
      sudo systemctl start metrics
      
      sudo systemctl enable metrics

      echo "S'ha completat"
    register: stdout
  - name: debug
    debug: msg={{stdout}}
