- name: My first play
  hosts: servers
  become: yes
  tasks:
  - name: ls
    shell: |
      wget -c https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
    register: stdout
  - name: debug
    debug: msg={{stdout}}
